apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: ai-image-serving
  namespace: ms-models
spec:
  predictor:
    containers:
      - name: kserve-container
        image: khuni1/ai-image-serving:latest
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
            ephemeral-storage: "500Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "1Gi"
