apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ms-frontend
  namespace: ms-frontend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0" # 서버리스 동작 허용
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        - image: xxhyeok/ms-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
