apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ms-backend
  namespace: ms-backend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0" # serverless 동작을 위해 0으로 설정
        autoscaling.knative.dev/maxScale: "5" # 최대 5개 Pod까지 확장 가능
        # 자동 스케일링 설정
        autoscaling.knative.dev/target: "50" # 트래픽 부하 기준점 (요청 개수 기준)
    spec:
      initContainers:
        - name: wait-for-database
          image: busybox:1.35
          command:
            [
              "sh",
              "-c",
              "until nc -z -w 2 database 5432; do echo 'Waiting for database...'; sleep 2; done",
            ]
      containers:
        - image: xxhyeok/ms-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILE
              value: prod
            - name: DATASOURCE_URL
              value: jdbc:postgresql://database:5432/cc-term
            - name: DATASOURCE_USERNAME
              value: user
            - name: DATASOURCE_PASSWORD
              value: "1234"
