apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ms-frontend
  namespace: ms-frontend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0" # serverless 동작을 위해 0으로 설정
        autoscaling.knative.dev/maxScale: "5" # 최대 5개 Pod까지 확장 가능
    spec:
      containers:
        - image: khuni1/ms-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
