apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ms-frontend
  namespace: ms-frontend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"  # 항상 Pod 1개 유지 (not serverless)
    spec:
      containers:
        - image: khuni1/ms-front:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
