apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: pytorch-serving
spec:
  supportedModelFormats:
    - name: pytorch
      version: "1"
      autoSelect: true
  containers:
    - name: kserve-container
      image: kserve/torchserve-kfs:latest
      command:
        - "torchserve"
        - "--start"
        - "--ncs"
        - "--model-store=/mnt/models/model-store"
        - "--ts-config=/mnt/models/config/config.properties"
      args: []
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /mnt/models
          name: model-storage
  volumes:
    - name: model-storage
      emptyDir: {}
