apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: api-gateway-jwt
  namespace: ms-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  jwtRules:
    - issuer: "https://auth.ms-serving.local"
      jwksUri: "https://auth.ms-serving.local/.well-known/jwks.json"
      forwardOriginalToken: true
      fromHeaders:
        - name: Authorization
          prefix: "Bearer "
