apiVersion: v1
kind: Namespace
metadata:
  name: ms-gateway
  labels:
    istio-injection: enabled
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-gateway
  namespace: ms-gateway
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/target: "50"
    spec:
      containers:
        - image: xxhyeok/ms-api-gateway:latest
          ports:
            - containerPort: 8088
          env:
            - name: BACKEND_URL
              value: http://ms-backend.ms-backend.svc.cluster.local
            - name: ALLOWED_ORIGINS
              value: http://localhost:3000
